config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :recipes do
    member do
      get :delete
    end
  end

  resources :categories do
    member do
      get :delete
    end
  end

  root "recipes#index"
  
end

app/models/category.rb
class Category < ActiveRecord::Base

  # Associations
  has_many :recipes

  # Validation rules
  validates :name, presence: true, length: { maximum: 255 }

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  # Associations
  belongs_to :user
  belongs_to :category
  has_many :ingredients
  has_many :directions

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions,  reject_if: :all_blank, allow_destroy: true

  # Validation rules
  validates :title,       presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { minimum: 10  }

  # Paperclip configuration - File uploading
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment  :image, content_type: { content_type: /\Aimage\/.*\z/ }, size: { in: 0..20.kilobytes }

end

app/models/role.rb
class Role < ActiveRecord::Base

  # Associations
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  belongs_to :role
  has_many :recipes

  # Callbacks
  before_create :set_default_role

  private
  
  def set_default_role
    self.role ||= Role.find_by_name('editor')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def user_not_authorized
    redirect_to root_path, alert: "Restrict access, you don't have the privileges to access this page!"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :set_category, only: [:show, :edit, :update, :delete, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_recipe, only: [:show, :edit, :update, :delete, :destroy]
  before_action :list_categories, only: [:index, :show]

  def index
    @recipes = Recipe.all.includes(:category)
    @recipes = @recipes.includes(:user) if user_signed_in?

    unless params[:category].blank?
      category_id = Category.find(params[:category]).id      
      @recipes = @recipes.where(category_id: category_id)
    end
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
  end

  def edit
    authorize @recipe
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    authorize @recipe
  end

  def destroy
    
    @recipe.image = nil
    @recipe.destroy
    
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, :category_id, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end

    def list_categories
      @categories = Category.all().order("name")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/application/_flash.html.haml
= content_tag :div, alert, class: "alert alert-warning" if alert
= content_tag :div, notice, class: "alert alert-success" if notice

app/views/application/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} RailsCooking
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to "Recipes", root_path
        %li
          = link_to "New Recipe", new_recipe_path
        -if user_signed_in? && current_user.role.name == "admin"
          %li
            = link_to "Categories", categories_path
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li
            = link_to "Logged in #{current_user.name}", edit_user_registration_path
          %li
            = link_to "Logout", destroy_user_session_path, :method => :delete
        -else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/application/_sidebar.html.haml
- if @categories.any?
  .list-group
    = link_to "All recipes", root_path, class: "list-group-item active"
    - @categories.each do |category|
      = link_to category.name, recipes_path(category: category.id), class: "list-group-item"

app/views/categories/_form.html.haml
= simple_form_for(@category, html: { class: "form-horizontal", novalidate: true }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-group
    = f.button :submit, class: "btn btn-primary"

app/views/categories/delete.html.haml
%h1.page-header Delete: #{@category.name}

= simple_form_for @category, url: category_path, method: :delete, html: { novalidate: true } do |f|
  
  .alert.alert-warning
    %p 
      You are about to delete this category.
      Note that this action cannot be undone. 
      Are you sure want to proceed?
    %p 
      %strong Recipe: #{@category.name}

  .form-group
    = f.button :submit, "Yes, Delete it!", class: "btn btn-danger btn-lg"
    = link_to "No, I've changed my mind", categories_path, class: "btn btn-success btn-lg"

app/views/categories/edit.html.haml
.row
  .col-md-4.col-md-offset-3

    %h1.page-header Edit #{@category.name}

    = render 'form'

    = link_to 'Show', @category
    \|
    = link_to 'Back', categories_path

app/views/categories/index.html.haml
.row
  .col-md-6.col-md-offset-3
    
    = link_to 'New Category', new_category_path, class: "btn btn-primary pull-right"

    %h1.page-header Listing categories

    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th

      %tbody
        - @categories.each do |category|
          %tr
            %td= category.name
            %td
              .btn-group
                = link_to 'Show', category, class: "btn btn-sm btn-default"
                = link_to 'Edit', edit_category_path(category), class: "btn btn-sm btn-warning"
                = link_to 'Destroy', delete_category_path(category), class: "btn btn-sm btn-danger"

app/views/categories/new.html.haml
.row
  .col-md-4.col-md-offset-3
  
    %h1.page-header New category

    = render 'form'

    = link_to 'Back', categories_path

app/views/categories/show.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1.page-header= @category.name

    .btn-group
      = link_to "Back", categories_path, class: "btn btn-default"
      = link_to "Edit", edit_category_path(@category), class: "btn btn-warning"
      = link_to "Delete", delete_category_path, class: "btn btn-danger"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RailsCooking
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body

    = render "nav"
    
    %section.main.container
      
      = render "flash"

      = yield
    
    %footer.footer
      .container
        %p.text-muted &copy; RailsCooking
    
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/recipes/_direction_fields.html.haml
.nested-fields
  = f.input :step, input_html: { class: "form-control", rows: 3 }, as: :text
  = link_to_remove_association "Remove", f, class: "btn btn-xs btn-danger"
  %br

app/views/recipes/_form.html.haml
- if @recipe.errors.any?
  .alert.alert-danger
    %h3= "#{pluralize(@recipe.errors.count, "error")} prohibited this recipe from being saved:"
    %ul
      - @recipe.errors.full_messages.each do |msg|
        %li= msg

= simple_form_for(@recipe, html: { class: "form-horizontal", novalidate: true }) do |f|
  .form-group.row
    .col-md-3
      = f.input :image, as: :file, input_html: { class: "form-control" }

  .form-group.row
    .col-md-3
      = f.input :category_id, :collection => Category.all, :label_method => :name, :value_method => :id, :label => "Categories", :prompt => "-- Select Category --", class: "form-control"

  .form-group.row
    .col-md-12
      = f.input :title, label: "What's the name of your recipe ?", input_html: { class: "form-control" }
  
  .form-group.row
    .col-md-12
      = f.input :description, as: :text, label: "Tell us a few words about your recipe", input_html: { class: "form-control", rows: 4 }

  .row
    .col-md-5
      %h4 Ingredients
      #ingredients
        = f.simple_fields_for :ingredients do |ingredient|
          = render "ingredient_fields", f: ingredient
        .links
          = link_to_add_association "Add", f, :ingredients, class: "btn btn-xs btn-success"

    .col-md-5.col-md-offset-1
      %h4 Directions
      #directions
        = f.simple_fields_for :directions do |direction|
          = render "direction_fields", f: direction
        .links
          = link_to_add_association "Add", f, :directions, class: "btn btn-xs btn-success"
  
  %br
  .form-group.row
    .col-md-12
      = f.button :submit, btn_text, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.nested-fields
  = f.input :name, input_html: { class: "form-control" }
  = link_to_remove_association "Remove", f, class: "btn btn-xs btn-danger pull-right"

app/views/recipes/delete.html.haml
%h1.page-header Delete: #{@recipe.title}

= simple_form_for @recipe, url: recipe_path, method: :delete, html: { novalidate: true } do |f|
  
  .alert.alert-warning
    %p 
      You are about to delete this recipe.
      Note that this action cannot be undone. 
      Are you sure want to proceed?
    %p 
      %strong Recipe: #{@recipe.title}

  .form-group
    = f.button :submit, "Yes, Delete it!", class: "btn btn-danger btn-lg"
    = link_to "No, I've changed my mind", recipes_path, class: "btn btn-success btn-lg"

app/views/recipes/edit.html.haml
%h1.page-header Edit: #{@recipe.title}

= render :partial => "form", :locals => { :btn_text => "Edit" }

= link_to 'Show', @recipe
\|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
.row
  %section.col-md-9
    - @recipes.each_slice(3) do |recipes|
      .row
        -recipes.each do |recipe|
          .col-md-4.text-center
            
            = link_to (image_tag recipe.image.url, class: "img-thumbnail"), recipe if recipe.image.exists?
            
            %h3= link_to recipe.title, recipe
            
            %p= recipe.category.name
            
            = simple_format recipe.description
            
            .btn-group
              = link_to "Read more", recipe, class: "btn btn-sm btn-default"
              - if user_signed_in?
                = link_to "Edit", edit_recipe_path(recipe), class: "btn btn-sm btn-warning" if policy(recipe).edit?
                = link_to "Destroy", delete_recipe_path(recipe), class: "btn btn-sm btn-danger" if policy(recipe).delete?
  %aside.col-md-3
    = render "application/sidebar"

app/views/recipes/new.html.haml
%h1.page-header New recipe

= render :partial => "form", :locals => { :btn_text => "Save" }

= link_to 'Go Back', recipes_path

app/views/recipes/show.html.haml
.row
  %section.col-md-9
    %h1.page-header #{@recipe.title}

    %p Category: #{@recipe.category.name} &bull; Made by #{@recipe.user.name} on #{@recipe.created_at.strftime("%d %B %Y, %H:%M")}

    = image_tag @recipe.image.url, class: "img-thumbnail" if @recipe.image.exists?

    %p
      %strong Description:
      %br
      = simple_format @recipe.description

    .row
      .col-md-3
        %h4 What do you need
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li= ingredient.name

      .col-md-5.col-md-offset-1
        %h4 How to cook it
        %ol
          - @recipe.directions.each do |direction|
            %li= direction.step

    %p.lead Bon appétit!

    .btn-group
      = link_to "Back", recipes_path, class: "btn btn-default"
      - if user_signed_in?
        = link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-warning" if policy(@recipe).edit?
        = link_to "Delete", delete_recipe_path, class: "btn btn-danger" if policy(@recipe).delete?
  %aside.col-md-3
    = render "application/sidebar"